<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "../api";
  import type { ApprovalView, SessionSummary, TaskView } from "../apiTypes";
  import PageState from "../components/PageState.svelte";
  import { relativeTime } from "../format";
  let sessions = $state<SessionSummary[] | null>(null); let tasks = $state<TaskView[] | null>(null); let approvals = $state<ApprovalView[] | null>(null); let unavailable = $state(false);
  async function load() { unavailable = false; try { [sessions, tasks, approvals] = await Promise.all([api.sessions(), api.tasks(), api.approvals()]); } catch { unavailable = true; } }
  const activeTasks = $derived((tasks ?? []).filter((task) => ["queued", "running", "paused"].includes(task.status)));
  onMount(load);
</script>
<section class="workbench" aria-labelledby="workbench-title"><div class="intro"><div><p class="eyebrow">Home / Workbench</p><h2 id="workbench-title">Pick up where your work left off.</h2><p>Every prompt, task, and decision remains scoped to the active project and governed by the server.</p></div><button class="btn btn-ghost btn-sm" type="button" onclick={load}>Refresh</button></div><section class="composer card" aria-label="Start governed work"><h3>What would you like to do?</h3><p>Start a new conversation, or resume a saved session. Raiker will show approvals before a gated action proceeds.</p><div><a class="btn btn-primary" href="#/new-chat">Start a conversation</a><a class="btn btn-ghost" href="#/tasks">Plan work</a></div></section>{#if unavailable}<PageState state="error" title="Workbench is temporarily unavailable" detail="Refresh to retry. No work was started or changed." />{:else if sessions === null || tasks === null || approvals === null}<PageState state="loading" title="Loading your workbench…" />{:else}<div class="grid"><section class="card"><div class="card-head"><h3>Waiting for you</h3><a href="#/approvals">Review approvals</a></div><strong class="metric">{approvals.length}</strong><p>{approvals.length === 1 ? "decision needs your review" : "decisions need your review"}. Approving never bypasses the server’s checks.</p></section><section class="card"><div class="card-head"><h3>Active work</h3><a href="#/work">Open live board</a></div><strong class="metric">{activeTasks.length}</strong><p>{activeTasks.length === 1 ? "task is open" : "tasks are open"}. You can stop work safely from its task card.</p></section></div><section class="card resumes"><div class="card-head"><h3>Resume a conversation</h3><a href="#/sessions">All sessions</a></div>{#if sessions.length === 0}<p>No saved conversations yet. Start with a focused request above.</p>{:else}<ul>{#each sessions.slice(0, 4) as session (session.session_id)}<li><a href={`#/new-chat?session=${encodeURIComponent(session.session_id)}`}>{session.title || "Untitled conversation"}</a><span>{session.turn_count} turns · updated {relativeTime(session.updated_at)}</span></li>{/each}</ul>{/if}</section>{/if}</section>
<style>.workbench{max-width:70rem;display:grid;gap:var(--space-4)}.intro,.card-head{display:flex;justify-content:space-between;gap:var(--space-3);align-items:flex-start}.intro h2{margin:.15rem 0;font-size:clamp(1.45rem,3vw,2.1rem)}.intro p,.composer p,.card p{color:var(--text-2);max-width:65ch}.eyebrow{color:var(--accent)!important;font-size:.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.composer{display:grid;gap:var(--space-2);padding:var(--space-5)}.composer h3,.card h3{margin:0}.composer div{display:flex;gap:var(--space-2);flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-4)}.card-head a,.resumes a{font-size:.84rem}.metric{display:block;font-size:2.25rem;margin-top:var(--space-3)}.resumes ul{list-style:none;margin:var(--space-2) 0 0;padding:0}.resumes li{border-top:1px solid var(--border);display:grid;gap:.2rem;padding:var(--space-3) 0}.resumes li span{font-size:.8rem;color:var(--text-3)}@media(max-width:40rem){.intro,.card-head{flex-direction:column}.grid{grid-template-columns:1fr}}</style>
