# SPDX-License-Identifier: Apache-2.0
"""Generate the web client's read-model types from the backend views.

OPT-01. ``web/src/lib/apiTypes.ts`` was a hand-written copy of the backend's
read models, held to them by a field-presence check
(``scripts/check_api_contract.py``). A view whose JSON is exactly its fields —
it inherits :class:`raiker.contracts.views.View` and keeps the shared
``to_dict``, and so does everything it nests — has one honest TypeScript shape,
and that shape is derived here rather than copied: Pydantic reads the dataclass
annotations into JSON Schema (the same schema FastAPI publishes in OpenAPI), and
this module prints it as TypeScript.

A view that projects differently from its fields — omits, renames or derives a
key in its own ``to_dict`` — has no schema to derive, so it is left out and its
mirror stays hand-written under the field-presence check.

The output, ``web/src/lib/generated/apiViews.ts``, is machine-owned and
committed. ``--check`` regenerates it in memory and fails on any difference,
which is how CI keeps it from going stale (``tests/test_web_api_types.py``).

    python -m scripts.generate_web_api_types          # write
    python -m scripts.generate_web_api_types --check  # verify
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import sys
import typing
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from raiker.contracts.views import View
from scripts.check_api_contract import backend_dataclasses

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "web" / "src" / "lib" / "generated" / "apiViews.ts"

_HEADER = """\
// Generated by scripts/generate_web_api_types.py from the backend's read-model
// views. Do not edit: change the Python view and run
//   python -m scripts.generate_web_api_types
// CI fails when this file differs from what the views produce.
"""


def _nested_types(annotation: Any) -> list[type]:
    """Every class an annotation mentions, through unions and containers."""
    found: list[type] = []
    stack = [annotation]
    while stack:
        item = stack.pop()
        if isinstance(item, type):
            found.append(item)
        stack.extend(typing.get_args(item))
    return found


def _wire_is_fields(view: type, seen: set[type] | None = None) -> bool:
    """True when ``view``'s JSON is exactly its declared fields, all the way down."""
    seen = set() if seen is None else seen
    if view in seen:
        return True
    seen.add(view)
    if not (dataclasses.is_dataclass(view) and issubclass(view, View)):
        return False
    if view.to_dict is not View.to_dict:
        return False
    hints = typing.get_type_hints(view)
    for field in dataclasses.fields(view):
        for nested in _nested_types(hints[field.name]):
            if dataclasses.is_dataclass(nested) and not _wire_is_fields(nested, seen):
                return False
            if not dataclasses.is_dataclass(nested) and hasattr(nested, "to_dict"):
                return False
    return True


def generated_views() -> dict[str, type]:
    """The views whose TypeScript shape can be derived, by class name."""
    return {
        name: view
        for name, view in sorted(backend_dataclasses().items())
        if _wire_is_fields(view)
    }


def _literal(value: Any) -> str:
    return json.dumps(value)


def _ts(schema: dict[str, Any]) -> str:
    """One JSON Schema node as a TypeScript type expression."""
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            members: list[str] = []
            for option in schema[key]:
                rendered = _ts(option)
                if rendered not in members:
                    members.append(rendered)
            return " | ".join(members)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        if "prefixItems" in schema:
            items = ", ".join(_ts(item) for item in schema["prefixItems"])
            if schema.get("items") not in (None, False):
                items = f"{items}, ...{_wrap(_ts(schema['items']))}[]"
            return f"[{items}]"
        return f"{_wrap(_ts(schema.get('items', {})))}[]"
    if kind == "object":
        if "properties" in schema:
            return _object(schema, indent="  ")
        extra = schema.get("additionalProperties", True)
        value = "unknown" if extra in (True, {}) else _ts(extra)
        return f"Record<string, {value}>"
    return "unknown"


def _wrap(expression: str) -> str:
    return f"({expression})" if " | " in expression else expression


def _object(schema: dict[str, Any], *, indent: str) -> str:
    # Every member is required: ``view_to_dict`` sends each declared field,
    # defaulted or not, and only views whose wire is their fields are generated.
    lines = ["{"]
    for name, prop in schema["properties"].items():
        lines.append(f"{indent}  {name}: {_ts(prop)};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def _comment(text: str, width: int = 96) -> str:
    """``text`` as a JSDoc block wrapped to ``width`` columns."""
    text = text.replace("*/", "* /")
    if len(text) + 7 <= width:
        return f"/** {text} */"
    lines = ["/**"]
    line = " *"
    for word in text.split():
        if len(line) + 1 + len(word) > width:
            lines.append(line)
            line = " *"
        line += f" {word}"
    lines += [line, " */"]
    return "\n".join(lines)


def render() -> str:
    """The whole generated module, deterministically ordered."""
    views = generated_views()
    _keys, schema = TypeAdapter.json_schemas(
        [(name, "serialization", TypeAdapter(view)) for name, view in views.items()],
        ref_template="#/$defs/{model}",
    )
    definitions: dict[str, Any] = schema.get("$defs", {})
    chunks = [_HEADER]
    for name in sorted(definitions):
        definition = definitions[name]
        doc = definition.get("description")
        if doc:
            # The docstring's first paragraph, which is its summary.
            summary = " ".join(str(doc).strip().split("\n\n")[0].split())
            chunks.append(_comment(summary))
        if definition.get("type") == "object" and "properties" in definition:
            chunks.append(f"export interface {name} {_object(definition, indent='')}\n")
            continue
        expression = _ts(definition)
        if len(expression) > 80 and " | " in expression:
            expression = "".join(f"\n  | {member}" for member in expression.split(" | "))
        else:
            expression = f" {expression}"
        chunks.append(f"export type {name} ={expression};\n")
    return "\n".join(chunks).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            print(
                f"{OUTPUT.relative_to(REPO_ROOT)} is stale; run "
                "`python -m scripts.generate_web_api_types`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.name} is current ({len(generated_views())} views)")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(expected.encode("utf-8"))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(generated_views())} views)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
